Update README.md
osisoft/sample-ocs-authentication_authorization-dotnet pull request #1
Opened 2021-01-13 23:36 UTC by cbardini

2021-01-14 15:05 UTC, kelseyduffy commented on README.md
> +This client uses the OAuth2/OIDC Authorization Code Flow + PKCE to obtain an access token. See the main OCS Authentication samples page [README](https://github.com/osisoft/OSI-Samples-OCS/blob/master
this links back to the main OCS Samples page not specifically the main OCS Authentication samples page. I would change the url link, or alternatively change the wording of the link to remove the word 'Authentication'
https://github.com/osisoft/OSI-Samples-OCS/blob/master/docs/AUTHENTICATION_README.md

2021-01-14 15:05 UTC, kelseyduffy requested changes
see auth link comment

2021-01-22 20:06 UTC, derekendres approved these changes

2021-01-22 20:11 UTC, kelseyduffy approved these changes

2021-01-22 20:14 UTC, merged